version: "3.9"
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - api
        command: 
            - redis-server 
            - --requirepass
            - ${REDIS_PASSWORD}
        volumes: 
            - redis_data:/data
    postgres:
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - DATABASE_HOST=api 
        ports:
            - '5432:${POSTGRES_PORT}'
        networks:
            - api
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
    web: 
        build: .
        ports: 
            - "${API_PORT}:${API_PORT}"
        links: 
            - redis
            - postgres
        depends_on: 
            - postgres
        networks:
            - api
        environment:
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USERNAME=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - API_PORT=${API_PORT}
            - ENVIRONMENT=${ENVIRONMENT}
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        depends_on: 
            - postgres
        ports: 
            - "5050:80"
        networks: 
            - api
networks:
    api:
        driver: bridge

volumes: 
    postgres_data:
    redis_data: